---
- name: Ensure YARN local directory exists
  ansible.builtin.file:
    path: "{{ yarn_nodemanager_local_dirs }}"
    state: directory
    owner: yarn
    group: hadoop
    mode: "0755"
  become: true
  when: "'workers' in group_names"

- name: Ensure YARN log directory exists
  ansible.builtin.file:
    path: "{{ yarn_nodemanager_log_dirs }}"
    state: directory
    owner: yarn
    group: hadoop
    mode: "0755"
  become: true
  when: "'workers' in group_names"

- name: Deploy yarn-site.xml
  ansible.builtin.template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/yarn-site.xml"
    owner: root
    group: hadoop
    mode: "0644"
  become: true

- name: Deploy mapred-site.xml
  ansible.builtin.template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/mapred-site.xml"
    owner: root
    group: hadoop
    mode: "0644"
  become: true

- name: Configure YARN JMX Exporter options
  ansible.builtin.blockinfile:
    path: "{{ hadoop_conf_dir }}/yarn-env.sh"
    marker: "# {mark} ANSIBLE MANAGED YARN JMX EXPORTER"
    block: |
      {% if 'master' in group_names %}
      export YARN_RESOURCEMANAGER_OPTS="$YARN_RESOURCEMANAGER_OPTS -javaagent:{{ jmx_exporter_jar }}={{ jmx_resourcemanager_port }}:{{ jmx_exporter_dir }}/hadoop-jmx.yml"
      {% endif %}
      {% if 'workers' in group_names %}
      export YARN_NODEMANAGER_OPTS="$YARN_NODEMANAGER_OPTS -javaagent:{{ jmx_exporter_jar }}={{ jmx_nodemanager_port }}:{{ jmx_exporter_dir }}/hadoop-jmx.yml"
      {% endif %}
    create: true
    owner: root
    group: hadoop
    mode: "0644"
  become: true